version: '3.3'
services:
  nginx:
    image: 'nginx'
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - cat
      - frontend
  frontend:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    image: 'sleepinglotus/ospc-client'
    container_name: frontend
    environment: 
      - NEXT_PUBLIC_URL_SERVER=cat:3000/graphql
      - NEXT_PUBLIC_URL=localhost/backend/graphql
    depends_on:
      - cat
  redisCommander:
    image: 'rediscommander/redis-commander'
    container_name: rediscommander
    env_file: 
      ./.env
    ports:
      - "8081:3000"
  cat:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile.prod
    image: 'sleepinglotus/ospc-api'
    container_name: cat
    env_file: 
      ./.env
    stdin_open: true
    tty: true
  # mongodb:
  #   image: 'mongo:4.4'
  #   container_name: mongodb
  #   restart: always
  #   ports: 
  #     - "27017:27017"
  #   volumes:
  #     - ~/etc/data/db:/data/db
