ersion: '3.7'
services:
  nginx:
    image: 'nginx'
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    volumes:
      - ./nginx/production.conf:/etc/nginx/nginx.conf
      - ~/etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - cat
      - frontend
  frontend:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    image: 'sleepinglotus/ospc-client'
    container_name: frontend
    depends_on:
      - cat
  cat:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile.prod
    image: 'sleepinglotus/ospc-api'
    container_name: cat
    depends_on:
      - mongodb
    env_file: 
      ./.env
    stdin_open: true
    tty: true
  mongodb:
    image: 'mongo:4.4'
    container_name: mongodb
    restart: always
    volumes:
      - ~/etc/data/db:/data/db
