FROM node:12.13.0-alpine As development

RUN apk update && apk add build-base git python

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY . .

EXPOSE 3000

CMD ["yarn", "start:dev" ]