version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: 'khaalid-subaan/server-dev:latest'
    container_name: selp-dev

    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  mongodb:
    image: 'mongo:4.4'
    container_name: mongodb
    restart: always
    volumes:
      - /data/db:/mongodat
    ports:
      - '27017:27017'

    # command: [--auth]
