version: '3.3'
services:
  nginx:
    image: 'nginx'
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    volumes:
      - ./nginx/production.conf:/etc/nginx/nginx.conf
      - ~/etc/letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - 443:443
    depends_on:
      - cat1
      - cat2
      - cat3
  cat1:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'khaalid-subaan/ospc-api'
    container_name: cat1
    ports:
      - '3050:3000'
    environment:
    - DB=mongodb
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  cat2:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'khaalid-subaan/ospc-api'
    container_name: cat2
    ports:
      - '3051:3000'
    environment:
    - DB=mongodb
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  cat3:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'khaalid-subaan/ospc-api'
    container_name: cat3
    ports:
      - '3052:3000'
    environment:
    - DB=mongodb
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  mongodb:
    image: 'mongo:4.4'
    container_name: mongodb
    restart: always
    volumes:
      - ~/etc/data/db:/data/db
    ports:
      - '27017:27017'
