# This is a basic workflow to help you get started with Actions

name: Develop

# Controls when the action will run. 
on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
    steps:
    - name: Use ansible 
      uses: arillso/action.playbook@master
      with:
        playbook: ansible/project_playbook.yml
        inventory: ansible/inentory
        private_key: ${{secrets.digital}}
        extra_vars: git_repo=https://github.com/Khaalidsub/OSPC-System.git project_src=./ospc
        tags: project
    
