# This is a basic workflow to help you get started with Actions

name: Develop

# Controls when the action will run. 
on:
  pull_request:
    branches:
    - main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
    steps:
    - uses: dawidd6/action-ansible-playbook@v2
    - name: Use ansible 
      with:
        playbook: project_playbook.yml
        directory: ./
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [all]
          ${{secrets.HOST}}@${{secrets.IP}}
        
        options: |
          --tags project
          --extra-vars project_src=./ospc
          --extra-vars git_repo=https://github.com/Khaalidsub/OSPC-System.git
          --verbose
    
